### ISSUE TITLE
error: mismatched types

### ISSUE THREAD

**Issue by chengchangwu** [cpjreynolds/rustty#8] opened 2015-08-07 08:06 UTC
I've tried your example. It gives the following error:

/home/ccwu/.cargo/registry/src/github.com-1285ae84e5963aae/rustty-0.1.8/src/core/termctl.rs:60:53: 60:63 error: mismatched types:
 expected `u32`,
    found `u64`
(expected u32,
    found u64) [E0308]
/home/ccwu/.cargo/registry/src/github.com-1285ae84e5963aae/rustty-0.1.8/src/core/termctl.rs:60             ioctl::read_into::<WindowSize>(self.fd, TIOCGWINSZ, &mut ws)

**Comment by cpjreynolds** [comment] 2015-08-12 22:11
First of all, thank you for reporting this!

Interesting, I can't reproduce this error on my dev box or the travis build. Looks like its because of a different ioctl function signature on your platform. What platform did you get this error on?

**Comment by chengchangwu** [comment] 2015-08-13 16:40
The example seems to work under 64-bit version of Ubuntu 14.04 LTS, but not under 32-bit version.

**Comment by cpjreynolds** [comment] 2015-08-13 21:26
I believe #12 should fix this, however I don't have a 32-bit machine to test it on. Closing the issue now as this should be fixed, but please let me know if you still get the error.

**Closed by cpjreynolds** 2015-08-13 21:26 UTC

**Comment by chengchangwu** [comment] 2015-08-14 05:01
it is fixed. Thank you.
